import "@fontsource/roboto"; /* Default weight */
import "@fontsource/roboto/400.css"; /* Specify weight if needed */
import "@fontsource/roboto/700.css"; /* Bold */
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "@/context/providers";
import { GenreProvider } from "@/context/GenreContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <GenreProvider>{children}</GenreProvider>
        </Providers>
      </body>
    </html>
  );
}
